name: frontend
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.1
  image_picker: ^0.8.4+2
  flutter_signature_pad: ^3.0.1
  path_provider: ^2.0.5
  syncfusion_flutter_signaturepad: ^23.1.36
  permission_handler: ^11.0.0
  flutter_sound: ^8.1.9
  assets_audio_player: ^3.0.3+3
  intl: ^0.18.1
  record: ^4.4.4
  audioplayers: ^5.1.0
  http: ^0.13.3
  http_parser: ^4.0.2
  flutter_svg: ^0.22.0
  google_fonts: ^4.0.4
  file_picker: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/container.png
